# Generated by Django 6.1.1 on 2026-09-20 14:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='ชื่อหมวด')),
                ('emoji', models.CharField(default='📦', max_length=8, verbose_name='รูปสัญลักษณ์')),
                ('color', models.CharField(default='#2563eb', max_length=20, verbose_name='สีพื้น')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'หมวดสินค้า',
                'verbose_name_plural': 'หมวดสินค้า',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อลูกค้า')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='เบอร์โทร')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ยังใช้งาน')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name': 'ลูกหนี้ (ซื้อเชื่อ)',
                'verbose_name_plural': 'ลูกหนี้ (ซื้อเชื่อ)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงินที่จ่าย')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลา')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='store.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'การชำระหนี้',
                'verbose_name_plural': 'การชำระหนี้',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย (บาท)')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ราคาทุน (บาท)')),
                ('emoji', models.CharField(default='🛒', help_text='ใส่อิโมจิให้อาม่าจำง่าย เช่น 🥤 🍜 🍫', max_length=8, verbose_name='รูปสัญลักษณ์')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปสินค้า')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=60, verbose_name='บาร์โค้ด')),
                ('unit', models.CharField(default='ชิ้น', max_length=20, verbose_name='หน่วย')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('track_stock', models.BooleanField(default=True, verbose_name='นับสต๊อก')),
                ('low_stock_alert', models.IntegerField(default=3, verbose_name='เตือนเมื่อเหลือน้อยกว่า')),
                ('is_favorite', models.BooleanField(default=False, help_text='สินค้าขายบ่อย ให้ขึ้นหน้าแรกตัวใหญ่ๆ', verbose_name='ปักหมุดหน้าแรก')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ยังขายอยู่')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category', verbose_name='หมวด')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
                'ordering': ['-is_favorite', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='เวลาขาย')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='ยอดรวม')),
                ('paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='รับเงินมา')),
                ('change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='เงินทอน')),
                ('payment_method', models.CharField(choices=[('cash', 'เงินสด'), ('transfer', 'โอน / สแกนจ่าย'), ('credit', 'ลงบัญชี (ซื้อเชื่อ)')], default='cash', max_length=20, verbose_name='วิธีจ่าย')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='หมายเหตุ')),
                ('is_void', models.BooleanField(default=False, verbose_name='ยกเลิกบิล')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='store.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'บิลขาย',
                'verbose_name_plural': 'บิลขาย',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ชื่อสินค้า')),
                ('emoji', models.CharField(default='🛒', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='จำนวน')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.sale')),
            ],
            options={
                'verbose_name': 'รายการในบิล',
                'verbose_name_plural': 'รายการในบิล',
            },
        ),
    ]
